### ISSUE TITLE
Error while installing AEM form Market place - Version 	8.2.0.32929

### ISSUE THREAD

**Issue by gowthamprabhus** [wttech/AEM-Rules-for-SonarQube#198]
2020.05.28 21:32:34 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.NoSuchMethodError: 'void com.google.common.base.Preconditions.checkArgument(boolean, java.lang.String, java.lang.Object, java.lang.Object)'
        at com.google.common.io.Resources.getResource(Resources.java:207)
        at com.cognifide.aemrules.extensions.RulesLoader.loadResource(RulesLoader.java:126)
        at com.cognifide.aemrules.extensions.RulesLoader.loadDescription(RulesLoader.java:119)
        at com.cognifide.aemrules.extensions.RulesLoader.createRule(RulesLoader.java:87)
        at com.cognifide.aemrules.extensions.RulesLoader.lambda$loadRule$0(RulesLoader.java:80)
        at java.base/java.util.Optional.map(Optional.java:265)
        at com.cognifide.aemrules.extensions.RulesLoader.loadRule(RulesLoader.java:80)
        at com.cognifide.aemrules.extensions.RulesLoader.load(RulesLoader.java:73)
        at com.cognifide.aemrules.extensions.AemRulesRulesDefinition.defineJavaRepository(AemRulesRulesDefinition.java:49)
        at com.cognifide.aemrules.extensions.AemRulesRulesDefinition.define(AemRulesRulesDefinition.java:33)
        at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:53)
        at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:120)
        at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
        at org.picocontainer.behaviors.Stored.start(Stored.java:110)
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:48)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:85)
        at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:46)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:82)
        at org.sonar.server.platform.PlatformImpl.executeStartupTasks(PlatformImpl.java:198)
        at org.sonar.server.platform.PlatformImpl.access$400(PlatformImpl.java:46)
        at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$1(PlatformImpl.java:122)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:370)
        at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:122)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:354)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020.05.28 21:32:35 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
2020.05.28 21:32:35 INFO  web[][o.s.s.n.NotificationDaemon] Notification service stopped

**Comment by toniedzwiedz** [comment]
Hi @gowthamprabhus, thanks for raising this. I believe the root cause is the same as that of #190, a bit of a mess with Guava versions at runtime.

This isn't the first time we've run into those. Given how tricky they've been to track down, we have a new version coming where we're removing Guava as a dependency. We'll keep you posted.

**Comment by toniedzwiedz** [comment]
Hi @gowthamprabhus , we're releasing v1.2, which should fix this. Sorry it took so long.
It should be posted in the Marketplace soon. In the meantime, you could have a try with the Jar file.
https://github.com/Cognifide/AEM-Rules-for-SonarQube/releases/tag/v1.2

**Comment by toniedzwiedz** [comment]
Hi @gowthamprabhus, have you tried installing version 1.2 from the Marketplace? Has it solved the issue?
