### ISSUE TITLE
Sonarqube crashes when AEM Rules plugin is installed

### ISSUE THREAD

**Issue by kunalsnehi** [wttech/AEM-Rules-for-SonarQube#200]
**Sonarqube is crashing when installing AEM Rules for SonarQube plugin 1.1 with the below error. Please help**

Dependency plugin - **Java Code Quality and SecurityLanguagesCode Analyzer for Java | 6.3 (build 21585)** installed

 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V
at com.google.common.io.Resources.getResource(Resources.java:207)
at com.cognifide.aemrules.extensions.RulesLoader.loadResource(RulesLoader.java:126)
 at com.cognifide.aemrules.extensions.RulesLoader.loadDescription(RulesLoader.java:119)
at com.cognifide.aemrules.extensions.RulesLoader.createRule(RulesLoader.java:87)
at com.cognifide.aemrules.extensions.RulesLoader.lambda$loadRule$0(RulesLoader.java:80)
at java.base/java.util.Optional.map(Optional.java:265)
at com.cognifide.aemrules.extensions.RulesLoader.loadRule(RulesLoader.java:80)
 at com.cognifide.aemrules.extensions.RulesLoader.load(RulesLoader.java:73)
 at com.cognifide.aemrules.extensions.AemRulesRulesDefinition.defineJavaRepository(AemRulesRulesDefinition.java:49)
 at com.cognifide.aemrules.extensions.AemRulesRulesDefinition.define(AemRulesRulesDefinition.java:33)
at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:56)
   at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:119)
 at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
 at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
 at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
  at org.picocontainer.behaviors.Stored.start(Stored.java:110)
  at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
 at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
 at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
  | 2020-06-25T23:53:41.214+02:00 | at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
  | 2020-06-25T23:53:41.214+02:00 | at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:47)
  | 2020-06-25T23:53:41.214+02:00 | at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:83)
  | 2020-06-25T23:53:41.214+02:00 | at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:46)
  | 2020-06-25T23:53:41.214+02:00 | at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:80)
  | 2020-06-25T23:53:41.214+02:00 | at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:196)
  | 2020-06-25T23:53:41.214+02:00 | at org.sonar.server.platform.Platform.access$400(Platform.java:46)
  | 2020-06-25T23:53:41.214+02:00 | at org.sonar.server.platform.Platform$1.lambda$doRun$1(Platform.java:121)
  | 2020-06-25T23:53:41.214+02:00 | at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
  | 2020-06-25T23:53:41.214+02:00 | at org.sonar.server.platform.Platform$1.doRun(Platform.java:121)
  | 2020-06-25T23:53:41.214+02:00 | at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
  | 2020-06-25T23:53:41.214+02:00 | at java.base/java.lang.Thread.run(Thread.java:835)

**Comment by epsilon-asutosh** [comment]
Noticed this works fine on Windows 10 with SQ 7.9.3 (LTS) and JDK 11.0.6, but it does not work on Mac OS with SQ 7.9.3 (LTS) with JDK 11.0.6 or 11.0.7

**Comment by cshawaus** [comment]
Same issue here with community edition 8.4.1.35646 running inside Docker.

**Comment by toniedzwiedz** [comment]
Hi, we're releasing v1.2, which should fix this. Sorry it took so long.
It should be posted in the Marketplace soon. In the meantime, you could have a try with the Jar file.
https://github.com/Cognifide/AEM-Rules-for-SonarQube/releases/tag/v1.2

I've tested this with the docker images for SonarQube Community 7.9.3 and 8.3.1 and the instance starts properly and registers the rules.
